<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Install Store Free</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c80e92da-3bee-4be0-8778-0ef866ec8022</testSuiteGuid>
   <testCaseLink>
      <guid>86f67d22-c6ce-44a7-a5a0-258259f5e9fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'huynh-ar-stag-2061'</defaultValue>
         <description></description>
         <id>88da770e-c2b5-471e-b4bf-d3d33a63f61e</id>
         <masked>false</masked>
         <name>raw_domain</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Alireview/Install new store free</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>746e1362-6d4c-46bf-98cc-591294353d9c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Store to install/Store3</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>746e1362-6d4c-46bf-98cc-591294353d9c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>store_name</value>
         <variableId>88da770e-c2b5-471e-b4bf-d3d33a63f61e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1b9c968-0a2e-405d-a11d-0eb3eb9a4cf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>067e371b-1cd6-48b7-975b-2fe266f1ad65</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
