<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close</name>
   <tag></tag>
   <elementGuidId>f269bf96-92dc-42dd-b90e-14c82bf018a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Polaris-ButtonGroup__Item_yiyol > button.Polaris-Button_r99lw > span.Polaris-Button__Content_xd1mk > span.Polaris-Button__Text_yj3uv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PolarisPortalsContainer']/div[15]/div/div/div/div/div/div[3]/div/div/div[2]/div/div/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-Button__Text_yj3uv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolarisPortalsContainer&quot;)/div[15]/div[1]/div[@class=&quot;Polaris-Modal-Dialog__Container_13mbo&quot;]/div[1]/div[@class=&quot;Polaris-Modal-Dialog_n3qgo&quot;]/div[@class=&quot;Polaris-Modal-Dialog__Modal_2v9yc&quot;]/div[@class=&quot;Polaris-Modal-Footer_z4ij5&quot;]/div[@class=&quot;Polaris-Modal-Footer__FooterContent_pymp5&quot;]/div[@class=&quot;Polaris-Stack_32wu2 Polaris-Stack--alignmentCenter_1rtaw&quot;]/div[@class=&quot;Polaris-Stack__Item_yiyol&quot;]/div[@class=&quot;Polaris-ButtonGroup_yy85z&quot;]/div[@class=&quot;Polaris-ButtonGroup__Item_yiyol&quot;]/button[@class=&quot;Polaris-Button_r99lw&quot;]/span[@class=&quot;Polaris-Button__Content_xd1mk&quot;]/span[@class=&quot;Polaris-Button__Text_yj3uv&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PolarisPortalsContainer']/div[15]/div/div/div/div/div/div[3]/div/div/div[2]/div/div/button/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We', &quot;'&quot;, 're currently importing your products into your store.')])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product import in progress'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/button/span/span</value>
   </webElementXpaths>
</WebElementEntity>
