<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Import</name>
   <tag></tag>
   <elementGuidId>ee08db29-3c55-48f4-951e-1c19438856fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.Polaris-ActionMenu-SecondaryAction_1dl4i > button.Polaris-Button_r99lw > span.Polaris-Button__Content_xd1mk > span.Polaris-Button__Text_yj3uv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='AppFrameMain']/div/div/div/div/div[2]/div/div/div/div/span/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-Button__Text_yj3uv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppFrame&quot;)/div[@class=&quot;Polaris-Frame_2qi9y Polaris-Frame--hasNav_wlvjn Polaris-Frame--hasTopBar_1162r&quot;]/main[@id=&quot;AppFrameMain&quot;]/div[@class=&quot;Polaris-Frame__Content_xd1mk&quot;]/div[@class=&quot;Polaris-Page_yisnh Polaris-Page--fullWidth_zyvh4&quot;]/div[@class=&quot;Polaris-Page-Header_z4uwg Polaris-Page-Header--hasActionMenu_1wx04 Polaris-Page-Header--noBreadcrumbs_bdstf Polaris-Page-Header--mediumTitle_bfol6&quot;]/div[@class=&quot;Polaris-Page-Header__Row_375v7&quot;]/div[@class=&quot;Polaris-Page-Header__RightAlign_1ok1p&quot;]/div[@class=&quot;Polaris-ActionMenu_1hlnt&quot;]/div[@class=&quot;Polaris-ActionMenu-Actions__ActionsLayout_w56ri&quot;]/div[@class=&quot;Polaris-ButtonGroup_yy85z Polaris-ButtonGroup--extraTight_1xh3x&quot;]/div[@class=&quot;Polaris-ButtonGroup__Item_yiyol&quot;]/span[@class=&quot;Polaris-ActionMenu-SecondaryAction_1dl4i&quot;]/button[@class=&quot;Polaris-Button_r99lw&quot;]/span[@class=&quot;Polaris-Button__Content_xd1mk&quot;]/span[@class=&quot;Polaris-Button__Text_yj3uv&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='AppFrameMain']/div/div/div/div/div[2]/div/div/div/div/span/button/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[2]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find products to sell'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add your products'])[1]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Import']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span/span</value>
   </webElementXpaths>
</WebElementEntity>
