<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_add_theme</name>
   <tag></tag>
   <elementGuidId>290b9ae7-ee6d-465c-a6c9-27ebf1a7954f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>document.querySelector(&quot;#UploadThemeModalActivator&quot;).forEach((el) => el.click())</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;UploadThemeModalActivator&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UploadThemeModalActivator</value>
      <webElementGuid>7d7f229e-b19a-4647-b3da-d9293718db99</webElementGuid>
   </webElementProperties>
</WebElementEntity>
