<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_publish_theme</name>
   <tag></tag>
   <elementGuidId>de78b036-0400-4f1a-92be-bebc5d043d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@title, 'Publish') and @name = 'app-modal-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>3c8c37c2-4e9e-473c-be87-4bbce165fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>app-modal-iframe</value>
      <webElementGuid>5cc816c4-cdb4-4b99-967b-eaa81dc0ebe2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
